### ISSUE TITLE
Implementing XLNet with IMDB cannot run

### ISSUE THREAD

**Issue by FatPupp** [asyml/texar-pytorch#139]
> Traceback (most recent call last):
  File "xlnet_classification_main.py", line 274, in <module>
    main(_args)
  File "xlnet_classification_main.py", line 166, in main
    iterator = tx.data.DataIterator(datasets)
  File "/home/yh/texar-pytorch/texar/torch/data/data/data_iterators.py", line 594, in __init__
    for name, dataset in datasets.items()}
  File "/home/yh/texar-pytorch/texar/torch/data/data/data_iterators.py", line 594, in <dictcomp>
    for name, dataset in datasets.items()}
  File "/home/yh/texar-pytorch/texar/torch/data/data/data_iterators.py", line 465, in __init__
    sampler = RandomSampler(dataset)
  File "/home/yh/texar-pytorch/texar/torch/data/data/data_iterators.py", line 167, in __init__
    data, replacement, num_samples)
  File "/home/yh/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Tried to change the default value of agrs such as replacement = True and num_samples =(some integer) of data_iterator.RandomSampler, but it doesn't work... Any advice would be appreciated!

**Comment by huzecong** [comment]
Thank you for the feedback, and sorry for the inconvenience. We have identified a bug in the IMDB data processor that failed to scan files under the appropriate directory, resulting in an empty dataset being created.

We will push the update shortly. After that, please update your code to the latest version and remove the cached dataset (by default under `examples/xlnet/processed_data`) before trying again.

**Comment by huzecong** [comment]
Fixed. Relevant pull request: #140.

**Comment by FatPupp** [comment]
Thanks a lot for the update! Best wishes.
