### ISSUE TITLE
utils.pad_and_concat cannot pad torch.LongTensor list

### ISSUE THREAD

**Issue by haoransh** [asyml/texar-pytorch#51]
`pad_and_concat` function cannot pad torch.LongTensor. For example

```
>>> a = [torch.tensor([[1,2]]), torch.tensor([[3]])]
>>> a[0].dtype
torch.int64
>>> texar.utils.pad_and_concat(a, 0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/haoransh/PycharmProjects/texar-pytorch/texar/utils/shapes.py", line 221, in pad_and_concat
    values[i] = torch.cat((v, padding), dim=pad_dim)
RuntimeError: Expected object of scalar type Long but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'
```

**Comment by huzecong** [comment]
Fixed by #52
