### ISSUE TITLE
Util bleu_moses.py does not work on windows

### ISSUE THREAD

**Issue by bigabig** [asyml/texar-pytorch#70]
Hey,

When for example executing the seq2seq attention example, the function `corpus_bleu_moses` in `bleu_moses.py ` is used to evaluate the current model. This does not work on windows:

```
Traceback (most recent call last):
  File "seq2seq_attn.py", line 190, in <module>
    main()
  File "seq2seq_attn.py", line 178, in main
    val_bleu = _eval_epoch('val')
  File "seq2seq_attn.py", line 172, in _eval_epoch
    hypotheses=hypos)
  File "c:\development\git\texar-pytorch\texar\evals\bleu_moses.py", line 154, in corpus_bleu_moses
    multi_bleu_cmd, stdin=hyp_input, stderr=subprocess.STDOUT)
  File "C:\Development\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Development\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Development\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Development\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

I fixed this error by changing line 147 of bleu_moses.py to
`multi_bleu_cmd = ["perl"] + [multi_bleu_path]`

I am not sure if this works without "perl" on Linux. Also, I don't know if you want to support Windows at all. But maybe you could state somewhere in the documentation that perl is required for some things (but I guess its already pre-installed on Linux, right?).

**Comment by huzecong** [comment]
I think this is because Windows bash environments do not support shebangs (that first line in a file that begins with `#!`, which indicates which program should be called to run the file).

@ZhitingHu What do you think of Windows support?

**Comment by gpengzhi** [comment]
Thank you for the feedback. @bigabig In this case, you could replace `tx.evals.corpus_bleu_moses(list_of_references=refs, hypotheses=hypos)` by `tx.evals.corpus_bleu(list_of_references=refs, hypotheses=hypos)` in Line 167.

**Comment by bigabig** [comment]
thank you, really appreciate your fast and good work on this project here! :)
